CREATE TABLE Users
(
    ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    -- auto_increment → IDENTITY in MSSQL
    EMAIL VARCHAR(256) UNIQUE NULL,
    -- UNIQUE constraint
    PASSWORD VARCHAR(256) NULL,
    ROLE VARCHAR(10) NULL,
    COLLEGE VARCHAR(100) NULL,
    COLLEGE_CODE VARCHAR(50) UNIQUE NULL,
    -- UNIQUE constraint
    STATUS VARCHAR(10) NULL DEFAULT 'PENDING',
    -- default value
    NAME VARCHAR(256) NULL,
    DATE VARCHAR(20) NULL
);

CREATE TABLE submissions
(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    PROBLEM_ID INT,
    TEAM_EMAIL VARCHAR(100),
    SOL_TITLE VARCHAR(100),
    SOL_DESCRIPTION TEXT,
    SUB_DATE DATE,
    STATUS VARCHAR(20) DEFAULT 'PENDING',
    SOL_LINK VARCHAR(256),
    FILES VARCHAR(256),
    MARK INT,
    CP_MARK INT,
    PS_MARK INT,
    BV_MARK INT,
    FP_MARK INT,
    IN_MARK INT
);


CREATE TABLE problems
(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    TITLE VARCHAR(100),
    DESCRIPTION TEXT,
    SUB_DEADLINE DATE,
    CATEGORY VARCHAR(50),
    DEPT VARCHAR(50),
    Reference VARCHAR(256),
    Evaluator_ID INT
);

CREATE TABLE Team_Members_List
(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NAME VARCHAR(50),
    SPOC_ID INT,
    EMAIL VARCHAR(100),
    PHONE VARCHAR(20),
    GENDER VARCHAR(10),
    ROLE VARCHAR(20),
    Team_ID INT
);

CREATE TABLE Team_List
(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NAME VARCHAR(50),
    SPOC_ID INT,
    LEAD_EMAIL VARCHAR(50),
    LEAD_PHONE VARCHAR(50),
    MENTOR_NAME VARCHAR(50),
    MENTOR_EMAIL VARCHAR(50)
);


