-- MySQL schema for the backend (table names match the queries in controllers/)
CREATE DATABASE IF NOT EXISTS Sakthi_auto;
USE Sakthi_auto;

CREATE TABLE IF NOT EXISTS Users (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    EMAIL VARCHAR(256) UNIQUE NULL,
    PASSWORD VARCHAR(256) NULL,
    ROLE VARCHAR(10) NULL,
    COLLEGE VARCHAR(100) NULL,
    COLLEGE_CODE VARCHAR(50) UNIQUE NULL,
    STATUS VARCHAR(10) NULL DEFAULT 'PENDING',
    NAME VARCHAR(256) NULL,
    PHONE VARCHAR(20) NULL,
    DATE VARCHAR(20) NULL
);

CREATE TABLE IF NOT EXISTS problems (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    TITLE VARCHAR(100),
    DESCRIPTION TEXT,
    SUB_DEADLINE DATE,
    CATEGORY VARCHAR(50),
    DEPT VARCHAR(50),
    Reference VARCHAR(256),
    Evaluator_ID INT
);

CREATE TABLE IF NOT EXISTS problem_evaluators (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    PROBLEM_ID INT,
    EVALUATOR_ID INT
);

CREATE TABLE IF NOT EXISTS submissions (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    PROBLEM_ID INT,
    TEAM_ID INT,
    TEAM_EMAIL VARCHAR(100),
    SOL_TITLE VARCHAR(100),
    SOL_DESCRIPTION TEXT,
    SUB_DATE DATE,
    STATUS VARCHAR(20) DEFAULT 'PENDING',
    SOL_LINK VARCHAR(256),
    FILES VARCHAR(256),
    MARK INT,
    CP_MARK INT,
    PS_MARK INT,
    BV_MARK INT,
    FP_MARK INT,
    IN_MARK INT
);

CREATE TABLE IF NOT EXISTS Team_List (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(50),
    SPOC_ID INT,
    LEAD_EMAIL VARCHAR(50),
    LEAD_PHONE VARCHAR(50),
    MENTOR_NAME VARCHAR(50),
    MENTOR_EMAIL VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS Team_Members_List (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(50),
    SPOC_ID INT,
    EMAIL VARCHAR(100),
    PHONE VARCHAR(20),
    GENDER VARCHAR(10),
    ROLE VARCHAR(20),
    Team_ID INT
);

CREATE TABLE IF NOT EXISTS Colleges (
    ID VARCHAR(20) PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    SPOC_ID INT NULL,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'Pending'
);

CREATE TABLE IF NOT EXISTS Spoc_Requests (
    ID VARCHAR(20) PRIMARY KEY,
    COLLEGE_NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(256) NOT NULL,
    DATE_REQUESTED DATE NOT NULL,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'Pending'
);
